### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by tocarevmax** [tocarevmax/DrumKick#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by tocarevmax** [comment]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by ajansel** [comment]
Looking great! Here are some thoughts: 
- When you try to sign up and it fails, then click on 'login', the state does not change (similar to how the errors would stay on the page). But, I actually don't think this is a bad thing because it makes it very easy for the user if they were on the same page! I just wanted to point it out to you incase it wasn't intentional and to point out some websites choose not to do this. 
- The only other feedback I have is that you need to have a demo login! Your nav bar looks so good that I would probably put it on the login and signup pages themselves.

**Comment by ajansel** [comment]
FYI once you have the demo user working I can close this issue

**Comment by tocarevmax** [comment]
- Demo User should work now. :)

**Comment by ajansel** [comment]
Nicely done!
